# @package _global_
visual_object_tracking_datasets: /mnt/HardDisk/datasets/SOT/GOT-10K/

sizes:
  search_image_size: ${tracker.instance_size}
  template_image_size: ${tracker.template_size}
  search_context: ${tracker.search_context}
  search_bbox_ratio: ${tracker.bbox_ratio}
  template_bbox_offset: ${tracker.template_bbox_offset}
  search_image_shift: 48
  search_image_scale: 0.35
  template_image_shift: 8
  template_image_scale: 0.05
  upscale_factor: 2
  context_range: 3

frame_offset: 70
# 控制训练数据中采样多少的负样本，负样本的presence字段为0, 如果negative_ratio为0，则表示丢弃所有的presence为0的样本
negative_ratio: 0
clip_range: True

dynamic_frame_offset:
  start_epoch: 20
  freq: 5
  step: 5
  max_value: 150

train:
  datasets:
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/train_data/
      sampling:
        _target_: model_training.dataset.track_sampling.TrackSampler
        data_path: /mnt/HardDisk/datasets/SOT/GOT-10K/train_ann_filter.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        clip_range: ${clip_range}
        num_samples: 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

val:
  img_size: 256
  ann_path:
  datasets:
    - name: got10k
      root_dir: /mnt/HardDisk/datasets/SOT/GOT-10K/
      subset: val

test:
  img_size: 256
  ann_path:
  datasets:
    - name: got10k
      root_dir: ${visual_object_tracking_datasets}/
      subset: val